repository_type: pipeline
nf_core_version: "3.3.1"

lint:
  files_exist:
    - CODE_OF_CONDUCT.md
  actions_awsfulltest: false
  actions_awstest: false
  pipeline_todos: false
  schema_ignore_params: "genomes"
