contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #asenext channel"
    url: https://nfcore.slack.com/channels/asenext
    about: Discussion about the nf-core/asenext pipeline
